# The URL the site will be built for
base_url = "https://enklht.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Jotted Down by enklht"
author = "enklht"
default_language = "ja"

theme = "kita"

taxonomies = [{ name = "tags" }]

[markdown]
  # Whether to do syntax highlighting
  # Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
  highlight_code = false

[extra]
  # Put all your custom variables here
  math = true

  [extra.profile]
    name = "Jotted Down by enklht"
    bio = "My personal space to explore the worlds of math & tech."
    avatar_url = "images/enklht.webp"
  [[extra.menu]]
    name = "Tags"
    url = "$BASE_URL/tags"
  [[extra.menu]]
    name = "Archive"
    url = "$BASE_URL/archive"
  [[extra.menu]]
    name = "About"
    url = "$BASE_URL/about"
